### ISSUE TITLE
Andesite/calcite copper ore drops as Andesite/calcite coal ore when mined with silk touch

### ISSUE THREAD

**Issue by LilyLicht** [DawnTeamMC/UniversalOres#11]
Like the title says, the ore drops as coal ore, rather than copper ore.

**Comment by LilyLicht** [comment]
Fix:

- \data\universal_ores\loot_tables\blocks\calcite_copper_ore.json
Line 28: universal_ores:calcite_coal_ore -> universal_ores:calcite_copper_ore

- \data\universal_ores\loot_tables\blocks\andesite_copper_ore.json
Line 28: universal_ores:andesite_coal_ore -> universal_ores:andesite_copper_ore

**Comment by Hugman76** [comment]
It is already fixed lol, thanks :D

**Comment by LilyLicht** [comment]
We love your mod, keep up the great work! (:
