### ISSUE TITLE
Recipes for cooking/blasting blackstone & basalt gold ores have the quartz ore variants as ingredients

### ISSUE THREAD

**Issue by ShinryuAspect** [DawnTeamMC/UniversalOres#20]
### What happened?

The recipes for both the Blasting and Smelting of the Blackstone/Basalt Gold Ore are messed up and it states you can obtain a Gold Ingot by smelting Blackstone/Basalt Quartz Ore, which means the actual ore variants of the Gold Ore are unused.
It's an easy fix, just editing the recipes inside the mod data folder (I've done it myself on my end) by changing the input from basalt/blackstone_quart_ore to basalt/blackstone_gold_ore.
Don't know if this minor conflict exists on older versions of the mod, I'm using the latest available for 1.19.

### Dawn API version

3.5.0

### Fabric API version

0.57.0+1.19

**Comment by Hugman76** [comment]
Holy shit I'm so sorry I'm just very dumb
