### ISSUE TITLE
Vanilla netherrack ores are not generating

### ISSUE THREAD

**Issue by LuigiDude248** [DawnTeamMC/UniversalOres#21]
### What happened?

Unsure if this is due in part on Universal ores part or Better Nether, but normal nether quartz ore and nether gold ore doesn't seem to spawn in the netherrack, only blackstone and basalt. Where their should be nether ore, only air seems to generate instead of the ore.

### Dawn API version

3.5.0

### Fabric API version

0.57.0+1.19

**Comment by Hugman76** [comment]
Huge mistake on my end. I'm so sorry about this.
If you want an explanation, instead of writing the `minecraft` namespace for the block IDs, I actually put the mod's - namespace. This will affect all versions of the mod. Except a patch version soon.
