### ISSUE TITLE
Blackstone Quartz to gold 1.18.2

### ISSUE THREAD

**Issue by oldjollysanta** [DawnTeamMC/UniversalOres#22]
### What happened?

![2022-07-24_13 42 31](https://user-images.githubusercontent.com/1407323/180631194-95d0df8e-f63c-4294-ba61-1b14fd795b60.png)
Two Smelting outputs for Blackstone Quartz ore (gold being the default)

I notice this is already fixed in the latest 1.19 update. Problem still exists in the 1.18.2 version

### Dawn API version

3.3.2

### Fabric API version

0.57.0+1.18.2

**Comment by Hugman76** [comment]
Fixed in v1.3.1. I'm fixing this only because you asked: I usually don't do updates to previous versions. :D
