### ISSUE TITLE
[Bug] Diorite, granite, and andesite doesn't seem to spawn?

### ISSUE THREAD

**Issue by Haihatu** [DawnTeamMC/UniversalOres#23]
### What happened?

Diorite, granite, and andesite doesn't seem to generate at all.
I believe it is this mod because of the issue as with vanilla quartz also not generating in the nether.

### Dawn API version

3.5.0

### Fabric API version

0.57.0+1.19

**Comment by Hugman76** [comment]
Shoud be fixed alongside #21
