### ISSUE TITLE
Blocks are unsynced with the server

### ISSUE THREAD

**Issue by MertsSavelii** [DawnTeamMC/UniversalOres#27]
### What happened?

In a single game everything is perfect, but on the server there is a strange generation and terrible brakes.
![2023-04-21_13 13 00](https://user-images.githubusercontent.com/77778323/233611271-2b244f68-6ebb-4308-861c-1d34121395ad.png)

### Dawn API version

4.2ю0

### Fabric API version

0.78.0+1.19.4

**Comment by Hugman76** [comment]
This bug has been reported for Promenade too. Therefore I must assume this is a Dawn API glitch. I have currently no idea on how to fix this.

**Comment by Hugman76** [comment]
This will be fixed with the Dawn API v4.2.1. Sorry about the huge delay on this issue.
