### ISSUE TITLE
Calcite variants (1.18)

### ISSUE THREAD

**Issue by RDKRACZ** [DawnTeamMC/UniversalOres#4]

**Comment by Dhranios** [comment]
The reason for this is because Calcite is not a stone variant in 1.17, it only generates as part of geodes.
Only in 1.18 experimental snapshots it became a stone variant, and the mod was not made for that.

**Comment by RDKRACZ** [comment]
Makes sense, now the question is - does the DawnTeamMC team have any plans for adding Calcite variants if there will be a 1.18 version of this mod?

**Comment by Dhranios** [comment]
Of course.
