### ISSUE TITLE
Some incorrect generation

### ISSUE THREAD

**Issue by JuceInUse** [DawnTeamMC/UniversalOres#5]
Hello! I love this mod, but am currently experiencing bugs relating to granite iron? For some reason, it doesn't seem to generate at all. Here's an example:
[https://media.discordapp.net/attachments/514848853678096384/880269580881244210/granite_iron_bug.jpg?width=884&height=676](Granite Iron bug)

**EDIT:** As it turns out, this is happening with all iron variants!

**EDIT 2:** Another thing! The mod itself entirely seems to break in new datapack biomes that change ore spawns, I think that was the issue 😅

**Comment by Hugman76** [comment]
The mod is incompatible with datapacks that override vanilla ore features themselves...
